### ISSUE TITLE
Allow Android Algorand Wallet to be Deep Linked with http:// or https://

### ISSUE THREAD

**Issue by avislash** [perawallet/pera-wallet#1]
The Android version of the Algorand Wallet currently only accepts algorand:// as the Deep Link prefix to launch the Algorand Wallet, however, there are some Android Applications which only allow hyperlinking if the link is prefixed with http// or https://. Please consider adding this as an option for allowing Android Developers/Users to launch the Algorand Wallet from within Android Applications. See screenshot below for an example. 

![image](https://user-images.githubusercontent.com/47284397/121761402-83b2c580-cafd-11eb-8136-a512a46eca3c.png)

**Comment by taylanpince** [comment]
We are working on this and will bring support for https://perawallet.app/... URLs to natively launch the app soon.
