### ISSUE TITLE
Ability to expand and hide the assets list

### ISSUE THREAD

**Issue by aorumbayev** [perawallet/pera-wallet#10]
Assume a scenario where user has 500 assets attached to his wallet. The current version of the app does not allow you to simply hide the assets, by default they are all displayed in a large expanded TableView.

Essentially, I think it is an important feature to have on the wallet, considering the fact that an average user involved with NFTS, most likely will hold more than 1 NFT. And having an option to hide the assets table to easily navigate between various wallets is a big improvement in UX.

**Comment by taylanpince** [comment]
We consider this resolved with the recent UI/UX enchancements.
