### ISSUE TITLE
Different response on Android and iOS app

### ISSUE THREAD

**Issue by vsobotka** [perawallet/pera-wallet#101]
We are using:
iOS app v5.6.0
Android Pera Wallet App v5.6.1
@walletconnect/client 1.8.0
@walletconnect/types 1.8.0
py-algorand-sdk==1.11.0

When using sendCustomRequest to sign multiple transactions, the responses on the mobile platforms are different. For example for our 4 transactions sign request, the Android app returns a single element in an array, while the iOS one returns four elements in an array, out of which only the third element contains any data, the rest are null.

This had to be caused by one of the latest Android app updates, as the version 5.4.2 was working just fine with our code, while the version 5.6.1 does not work, as it only return a single element.

**Comment by artizco** [comment]
Thanks for your report @vsobotka. We found the problematic part. We will fix it on the android app and release it soon.

**Comment by mogascan** [comment]
@vsobotka do you recall on what dApp this issue was observed?

**Comment by vsobotka** [comment]
@mogascan We encountered it in our app, not a dApp. We just have some integration for NFT features. It's a game called Sim Companies. But we adjusted our code to work with both formats.

**Comment by yigitguler** [comment]
This is fixed.
