### ISSUE TITLE
Please support sign LSIG from SDK

### ISSUE THREAD

**Issue by emg110** [perawallet/pera-wallet#102]
Signing Logic Sigs is a must for Web3 wallets! Please support it!

**Comment by pbennett** [comment]
LSIGs are the signature and are supported in atomic transaction groups passed through to Pera.
Do you mean Delegated Signatures ?  These are insanely dangerous.  dApps shouldn't be using these nor normalizing their use.  Users could _trivially_ sign away all rights to their account by signing a 1 line TEAL program.

**Comment by emg110** [comment]
Hey buddy! MG here! As it is clearly written I know the transactions are supported but I exactly meant the SIGNING of LOGIC SIGNATURES (signLogicSig() method which is available in MyAlgo wallet connect API) by Pera and if it is going to be supported or just dropped because it is dangerous (which is not a good reason for not supporting that method IMHO! For example, if you just create an LSIG for non-critical transactions like calling ABI methods with no payments or close out or... then they can be a very good tool to reduce the number of annoying signatures users get asked to provide while working with dApp.

**Comment by pbennett** [comment]
A regular lsig is by definition, already signed.  These work just fine w/ Pera.
*Delegated* signatures are crazy dangerous though and I don't think should be something signable by user wallets unless they popped up MASSIVE warnings (like alarm bells going off sort of thing) because users will never be able to look at the TEAL and verify its something safe to sign control of their keys over to that TEAL.

**Comment by emg110** [comment]
I completely agree with informing users and warnings and stuff but yet again the feature is there and like a knife can be used both to kill or to perform surgery! That does not make it unnecessary! It just needs more caution by developers and I 100% agree with you on that. Now back to the question, is this sensitive feature going to be supported as it is available on SDKs and also MYAlgo Wallet? Or just will be ignored and dropped because it can be dangerous as well? I just want to know the strategy and plan regarding this from Pera, so that as a Dev I can have my own plan based on the response! Million thanks for your answers dear Patrick!
