### ISSUE TITLE
Issues Building the iOS Project

### ISSUE THREAD

**Issue by yulianiii** [perawallet/pera-wallet#103]
When following the steps to build the iOS Project, the dependency command `pod install` yields error:
 `[!] No ``Podfile`` found in the project directory.`

Did you guys move away from cocopods or if the podfile missing?

**Comment by sakkaras** [comment]
@yulianiii It seems like the documentation is outdated. We are using SPM for a while, not cocoapods. Thanks for your warning, we will update the documentations.
