### ISSUE TITLE
wordlist doesnt match old algorand wallet wordlist

### ISSUE THREAD

**Issue by pcastelovigo** [perawallet/pera-wallet#107]
app refuses valid passphrases

**Comment by pcastelovigo** [comment]
"make" is in wordlist but pera refuses it

https://github.com/algorand/py-algorand-sdk/blob/develop/algosdk/wordlist.py

**Comment by modeth** [comment]
Are you still having the issues?

**Comment by mitsinsar** [comment]
Could you please describe your situation. 

I am checking Pera's wordlist and I see `make` is in the list. Can be seen [here - line 1108](https://github.com/perawallet/pera-wallet/blob/master/android/app/src/main/java/com/algorand/android/utils/PassphraseKeywordUtils.kt)
