### ISSUE TITLE
Cannot connect Pera Wallet from another app using WalletConnect

### ISSUE THREAD

**Issue by jasonhtpham** [perawallet/pera-wallet#108]
The issue happens might be because of the update on WalletConnect. I have tried multiple schemes following this [guide](https://github.com/perawallet/mobile-to-ios-wallet-connection) and comments in this [issue](https://github.com/perawallet/pera-wallet/issues/81#issuecomment-1507749646_):

`perawallet-wc://wc?uri=wc://7f838d9c-a772-4e32-acaf-a00da0c38cb2@1?bridge=https%3A%2F%2Fb.bridge.walletconnect.org&key=3091...`

`algorand://wc?uri=wc://7f838d9c-a772-4e32-acaf-a00da0c38cb2@1?bridge=https%3A%2F%2Fb.bridge.walletconnect.org&key=3091...`

`algorand-wc://wc?uri=wc://7f838d9c-a772-4e32-acaf-a00da0c38cb2@1?bridge=https%3A%2F%2Fb.bridge.walletconnect.org&key=3091...`

`https://perawallet.app/qr/perawallet-wc/wc?uri=wc:d2ad8fbc-5d92-425a-9e5b-24ddbfa6e9ed@1?bridge=https%3A%2F%2Fa.bridge.walletconnect.org&key=bf7...`

However, they all open the Pera Wallet app without the popup asking to connect the account.

**Comment by modeth** [comment]
@jasonhtpham Talk to Algorand Support on the [Live support page](https://dev-algo.online/) so that your issue can be looked into.

**Comment by jasonhtpham** [comment]
I tried and did not receive the needed support from the there.

**Comment by modeth** [comment]
Did you talk to the support?

**Comment by jasonhtpham** [comment]
Yes, after explaining in detail that I am developing on Flutter and this issue only happen on iOS, the supported did not get back to me. I am also asking for support in Pera Wallet Discord.

**Comment by jasonhtpham** [comment]
The scheme `perawallet-wc://wc?uri=` should work but need to make sure the URI is entirely encoded:
```
// Not work
perawallet-wc://wc?uri=wc://7f838d9c-a772-4e32-acaf-a00da0c38cb2@1?bridge=https%3A%2F%2Fb.bridge.walletconnect.org&key=3091...
// Works
perawallet-wc://wc?uri=wc%3A%2F%2F7f838d9c%2Da772%2D4e32%2Dacaf%2Da00da0c38cb2%401%3Fbridge%3Dhttps%253A%252F%252Fb%2Ebridge%2Ewalletconnect%2Eorg%26key%3D3091...
```
