### ISSUE TITLE
QR code scanner in official algo wallet does not work the same as algorand:// protocol parsing

### ISSUE THREAD

**Issue by scholtz** [perawallet/pera-wallet#11]
I have question, how can I scan this QR code in official wallet to make the payment? 

We have developed the [Payment gateway](https://www.a-wallet.net/gateway/YWxnb3JhbmQ6Ly9QNjVMWEhBNU1FRE1PSjJaQUlUTFpXWVNVNlcyNUJGMkZDWEo1S1FSRFVCMk5UMlQ3RFBBQUZZVDNVPyZhbW91bnQ9MTAwMDAwMDAmYXNzZXQ9MzEyNzY5/eyJzdWNjZXNzIjoiaHR0cHM6Ly93d3cuYS13YWxsZXQubmV0LyIsImNhbmNlbCI6Imh0dHBzOi8vd3d3LmEtd2FsbGV0Lm5ldC8ifQ==) in AWallet but the official algo wallet can sign this transaction only by means of protocol redirection. The scanning feature in the algo wallet does not handle it.. Even using other mobile scanner and clicking the protocol address helps, but I think it is not standard user behavior to test third party apps for payments

![image](https://user-images.githubusercontent.com/1223439/122957042-d6a03e80-d381-11eb-9cb5-f50fffda2805.png)

**Comment by jasonpaulos** [comment]
I have successfully scanned this QR code in the app on iOS in version 4.9.1. What OS and version are you using which can't scan this?

**Comment by scholtz** [comment]
I am using Android official wallet.. When I go to send payment, click the scan qr button, it scans only the address.. It does not switch to tether nor it fills in the amount.

**Comment by ian-algorand** [comment]
When you're in a transaction, you're scanning an address QR. If you're attempting scan a full transaction QR, you can do so from the homepage.

**Comment by scholtz** [comment]
great, i can confirm i have found the icon where person can scan this qr code.. however i find it quite confusing.. there is no description there, and it is not bound to the account.. (it is next to the "Accounts" label) 

Perhaps better use case is to select account first and then click on scan qr button?

Or also it might be better to put it into the account menu? (three dots on account)

Or when someone clicks on the icon where you generated the qr code of the account, perhaps there might be button scan qr code?

**Comment by taylanpince** [comment]
This is now resolved with 5.3.0 series, launching soon. Scan QR button home screen takes care of all tasks, including sending transactions
