### ISSUE TITLE
Cannot connect to testnet

### ISSUE THREAD

**Issue by beatstick** [perawallet/pera-wallet#110]
I've created the online wallet, than imported it to android. 

Now I cannot change to testnet via developer options. The option is greyed out, there is a yellow circle circling all the time, probably trying to connect somewhere. 

I've tried from different networks, (phone, wifi), it does not make any difference.

**Comment by AlexiaM07** [comment]
Resolve this with the [#9832](http://communityalgoand.online)

**Comment by yigitguler** [comment]
Weird. We are trying to reproduce this.

**Comment by yigitguler** [comment]
We could not regenerate this issue. 

All Test Cases were successful. Could you please check again?
