### ISSUE TITLE
Got "Request Expired or expiry param validation failed(MIN_INTERVAL: 300, MAX_INTERVAL:604800)" in Android Beta using WalletConnectv2

### ISSUE THREAD

**Issue by jingxuan98** [perawallet/pera-wallet#115]
Got "Request Expired or expiry param validation failed(MIN_INTERVAL: 300, MAX_INTERVAL:604800)" in Android Beta using WalletConnectv2

i am getting this error message after signing my 1st after connecting.
<img width="536" alt="Screenshot 2023-07-19 at 5 26 05 PM" src="https://github.com/perawallet/pera-wallet/assets/43902263/6fe3041e-cbe7-4e12-b059-580e981dc8de">

Steps to Reproduce:
1. In Android Beta ver, connect via wallectConnect
2. Sign a transaction and wait a while
3. Sign your 2nd or 3rd transaction

**Comment by yigitguler** [comment]
We are investigating this.

**Comment by yigitguler** [comment]
This is resolved with the latest version.
