### ISSUE TITLE
Mobile URL scheme stopped working on Android

### ISSUE THREAD

**Issue by elingersin1** [perawallet/pera-wallet#116]
ANDROID: Transfer ASA url scheme (which we are using to pay businesses on our app) stopped working with the new Pera wallet version that was released last week.

When opening scheme ex. perawallet://7N54HZSGBRQF7FW6YNC6F5H42AT5OXN3F5OQDAXF6H6PDFHNXIEBCJFHOY?amount=1000000&asset=226701642, it shows the screen to select account, but when tapping on the account, nothing happens.

Algo transfer doesn't work as well (ex. perawallet://7N54HZSGBRQF7FW6YNC6F5H42AT5OXN3F5OQDAXF6H6PDFHNXIEBCJFHOY?amount=1000000)

(on Android we're using the algorand:// for URL scheme as perawallet:// works only for ios)

**Comment by artizco** [comment]
Hi @elingersin1, thank you for the detailed report. We fixed this issue with v5.9.1. It will be available soon.
