### ISSUE TITLE
New: flag SCAM transactions within PeraWallet (& Explorer)

### ISSUE THREAD

**Issue by NFNomad** [perawallet/pera-wallet#122]
Hi @taylanpince @jasonpaulos,

Creator of Chaintrail.io & Algorand Scam Detector here. Lately there has been a massive surge in SCAM transactions being send towards random people their wallets. Although the transactions themselves aren't harmful, the note could be. If users see those notes (getting certain rewards/airdrops) and actually interact with them, they effectively could lose all their funds. 

Would it be possible for Pera Wallet to flag those transactions and show it to the user that they're SCAM? Either through a label on the transaction list view & a label / message on the transaction view itself. Both on the Wallet and the Explorer? That way we can work towards a future where scammers fail to succeed as all users are informed about it upfront. 

Integrating it is fairly simple (if you use the API). 
https://github.com/ChainTrail/algorand-scam-detector

Let me know if there are any questions.

**Comment by yigitguler** [comment]
We blocked the transactions at the wallet connecion level. The improved version will include an additional check at the app side. Thank you Chaintrail for providing this API! It is important for the community.
