### ISSUE TITLE
Security: 2FA Soft Token OTP

### ISSUE THREAD

**Issue by HashMapsData2Value** [perawallet/pera-wallet#15]
Currently, it is possible to connect a ledger device to get 2FA. But it might be nice if you could use a soft token style way (Authy, Google Authenticator, etc), setup on a different device.

Not a heavy priority.

**Comment by taylanpince** [comment]
Thank you, we've captured this on our roadmap: https://roadmap.perawallet.app/feature-requests/p/2fa-support-with-soft-token-otp
