### ISSUE TITLE
git clone fail when checkout 

### ISSUE THREAD

**Issue by sherlockhouse** [perawallet/pera-wallet#18]
Error: invalid path 'ios/Resources/Assets/Assets.xcassets/Accounts/Main/icon-qr-alert.imageset/icon-qr-alert".pdf'
克隆远程存储库时遇到错误: Git failed with a fatal error.
unable to checkout working tree
Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by jasonpaulos** [comment]
I cannot reproduce this error. What is the exact command you used to clone out this repo?

**Comment by softwarekinetics** [comment]
Having the same issue.  Using GitHub desktop, Win10, normal clone repository menu selection with URL.
![SharedScreenshot](https://user-images.githubusercontent.com/81371689/125061595-1bf78800-e073-11eb-9d34-a02f6d0addbc.jpg)

**Comment by jasonpaulos** [comment]
@softwarekinetics thank you for reproducing the error. I suspect that the issue is the `"` in the filename, which may not be valid in Windows. I'll see if we can change it.

**Comment by taylanpince** [comment]
File is no longer in the repo.
