### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by scholtz** [perawallet/pera-wallet#2]
I have read that the source code is not in here, so I will not create pull request for slovak translation.

I have translated the android app strings. Can you please put it to your devops?

https://apps.scholtz.sk/values-sk.zip

If you could spare some algos for my work, please donate to the address P65LXHA5MEDMOJ2ZAITLZWYSU6W25BF2FCXJ5KQRDUB2NT2T7DPAAFYT3U

**Comment by taylanpince** [comment]
We appreciate your contribution. To keep things standardized, we are working with a translation company that continuously translates strings for every release. We will consider adding Hungarian to our list of supported languages through them.
