### ISSUE TITLE
Would it be possible to have an asset with a photo?

### ISSUE THREAD

**Issue by joeygibson** [perawallet/pera-wallet#24]
Is it possible to have a photo show on an asset card, instead of just a solid color with the white circles?

Context: I bought my first Lofty.ai token yesterday, and sent it to the official Algorand wallet on my iPhone. It worked fine, and I can see it, but it's just a grey card shape, with concentric white circles, and some basic info about the asset. 

The asset I bought _does_ have a photo, which can be seen by looking it up in https://www.randgallery.com/, and a comment from a reddit said this:

> I made sure that the NFT viewers would be able to show the asset preview images, there's a special protocol that is used when requesting the metadata URLs that we respond to. The official wallet could easily implement the same.

**Comment by taylanpince** [comment]
For NFT assets, this is now fully supported. We are also bringing icons for ASAs as well.
