### ISSUE TITLE
IS THERE AN ELABORATE OPEN-SOURCED DESIGN ON HOW THE ALGORAND MOBILE WALLET WORKS?

### ISSUE THREAD

**Issue by kcelestinomaria** [perawallet/pera-wallet#26]
Hello there @ian-algorand @jasonpaulos , is there an elaborate open-sourced design chart on how the algorand mobile wallet works internally? I am trying to add several features to make it more accessible, but I do not understand deeply the design decisions made, which would help me be able to easily re-architect the app and add the features. Here is a Google Docs document on what I am building using your open-sourced wallet, thank you: https://docs.google.com/document/d/1CWJ4nfYReHVu4phA8sokMkrWEPSI_ZESbqXeJsI16mw/edit?usp=sharing, I hope you may respond, thank you.

**Comment by taylanpince** [comment]
Sorry you never got a response to this. No such document is currently available.
