### ISSUE TITLE
Fix Bottom Navigation Titles

### ISSUE THREAD

**Issue by jeremyv3** [perawallet/pera-wallet#30]
android/app/src/main/res/menu/bottom_navigation_menu.xml

android:title's for contactsFragment and notificationCenterFragment are reversed. Move string for History to Contacts and Contacts to History.

The corrected values are below
    <item
        android:id="@id/contactsFragment"
        android:title="@string/contacts" />

    <item
        android:id="@id/notificationCenterFragment"
        android:title="@string/history" />

Closing PR that was added.

**Comment by taylanpince** [comment]
Thank you
