### ISSUE TITLE
[iOS - critical bug] Transactions initiated via Schema URI are divided by 1000

### ISSUE THREAD

**Issue by andpay-io** [perawallet/pera-wallet#31]
Hi there,

We're using the Algorand Wallet as one of the main payment options within our payment platform &pay. However - when initiating a transaction via the Schema URI, the iOS wallet has a different behaviour then the Android one. 

It's quite an important bug, as currently the iOS wallet sending the wrong value. See screenshot attached for an overview of the difference. 

The amount being used was: 100000 microAlgo, so 0.1 ALGO. 
Android considers this as 0.1 ALGO throughout the signing process.
iOS starts with 0.1 ALGO, but as soon as you go towards preview. It switches towards 0.00001 ALGO (division of 1000).

Could this be reviewed and resolved within the next version? 
![ios-app-transaction-issue](https://user-images.githubusercontent.com/90002627/137594877-2341b4d4-a101-4e0d-9e94-ccc0f9048108.png)

**Comment by taylanpince** [comment]
This issue was resolved but we noticed a related problem that will also be resolved with 5.3.0.
