### ISSUE TITLE
Payment Prompt - QR code paring behaviour

### ISSUE THREAD

**Issue by ghost** [perawallet/pera-wallet#33]
When using an Algorand payment prompt, we are noticing two different behaviours when buyers try to scan the QR code.

### Scan from Homepage

The Algorand wallet scans the QR code with the asset id specifed but still asks the user to select an asset. Is this the expected behaviour?

### Scan from Send Transaction Screen

The Algorand wallet scans the QR code from the "Scan QR" button but silently ignores the amount and asset id mismatch. This has caused buyers to accidentally send the wrong amount or use a different asset than the one specified.

Is it possible to warn the user and ask them to re-scan the QR code from the homepage? The current behavior is causing some users to make mistakes and they have to create support tickets to manually resolve the issue.

### Sample Payment Prompt

Payment Prompt: algorand://7Y5T5MWBJP6OPY6NULXYBKXBWTWVMEGPO7GD7FE3TRPIEZC4UX3BOC76NU?amount=949069539&xnote=dXdK26WiTeSh3tZ8yDjcCg&asset=10458941

QR Code,
![image](https://user-images.githubusercontent.com/50232871/140627962-ff26d706-b792-4e44-9031-716a1d31a1af.png)

**Comment by yigitguler** [comment]
This issue is fully functional at the moment.
