### ISSUE TITLE
WalletConnect Issues - Duplicate Sessions, Scan QR Code

### ISSUE THREAD

**Issue by ghost** [perawallet/pera-wallet#34]
We have implemented the Algorand WalletConnect integration using the following developer documentation,
[developer.algorand.org/docs/get-details/walletconnect](https://developer.algorand.org/docs/get-details/walletconnect/)

We have used WalletConnect v1.6.5 as this was the version used in the [sample react app](https://github.com/algorand/walletconnect-example-dapp/blob/master/package.json).

After releasing the integration, we came across the following two issues.

### Duplicate Sessions

WalletConnect v1 sessions have an indefinite lifetime so we call killSession on the following events,
* Payment Completion
* Cancel and return to store
* Closing walletconnect tab

However, there are a few situations where the call to killSession does not complete (e.g. network issues, refreshing page, page unloads before killSession call completes) and causes multiple active sessions in the wallet. In this situation, sendCustomRequest calls do not seem to reach the wallet. The only way to recover is to manually disconnect all the sessions and start anew.

Is there anything we can do apart from providing a help message to the user asking them to clear out the WalletConnect sessions?

![Screenshot_20211107-092015 (2)](https://user-images.githubusercontent.com/50232871/140631983-81f2e125-ae92-4a4a-b2eb-4d76a5e49271.png)

### Scan QR Code

There are three places in the Algorand wallet where a user has the option to scan a QR code,
* Homepage
* From the "Send Transaction" screen
* From the WalletConnect Sessions settings screen

Some users are accustomed to going into the send transaction screen before making a payment. When they use the "Scan QR" button there, the wallet is unable to scan the WalletConnect QR code but does not show any warning or error message.

This causes frustration for the user as they have no information on what is wrong.

To provide better guidance to users would it be possible to change any of the following,
* Algorand Wallet - Provide a warning or error message which guides the user to use the homepage scan button.
* algorand-walletconnect-qrcode-modal - Provide additional info which recommends the user to scan the QR code from the homepage.

As a workaroud from our side, we have provided the old [payment prompt](https://developer.algorand.org/articles/payment-prompts-with-algorand-mobile-wallet/) as a fallback option and have added some instructions on how to scan the QR code.

However, the payment prompt has its own issues (#31, clicking on the URI on Android does not trigger a transaction) and we would like to migrate away from it.

![image](https://user-images.githubusercontent.com/50232871/140629993-9cd62cf3-0047-4fad-9906-6d5f6134150b.png)

**Comment by yigitguler** [comment]
This issue should be fixed now. Can you please check again?
