### ISSUE TITLE
Adding Asset from QR Code

### ISSUE THREAD

**Issue by barnjamin** [perawallet/pera-wallet#40]
When a user scans a QR code that contains a payment prompt URI to opt into an asset, the wallet app rejects the transaction with the message that they have not opted into the asset yet.

For an opt in transaction (sender me, receiver me, asset id != 0, amount 0) we should allow the user to sign the transaction, possibly with some information about what the effect will be.

**Comment by webjunkie** [comment]
Any update on this? Is there any way to trigger opting in to an asset?

We want our application to direct the user to a simple opt in, so we might transfer to them the asset.
