### ISSUE TITLE
Report iOS/Android and version when connecting using the WalletConnect

### ISSUE THREAD

**Issue by patrik7** [perawallet/pera-wallet#41]
When WalletConnect is used to create session with the app, the app sends the peerMeta data back.

It would be incredibly useful, if it was possible find out what exactly wallet connect connected with, namely:
- Is it the Android or iOS version of the app ?
- what version of the code exactly

I can already see the apps, iOS vs. android, behaving differently, and I assume in the future it will not be always possible to keep the codes in sync.

As the developer of the other side of the communication, I would like to know what exactly is on the other side.
![Screenshot from 2021-11-26 13-20-15](https://user-images.githubusercontent.com/4105845/143581093-66d3eb5a-0ec9-4123-ad11-4ad7c63f97a3.png)

**Comment by mitsinsar** [comment]
Hi Patrik! You are right, it would be nice to know as a dApp who the client is. But as far as I know, Official WalletConnect client accepts an object called `Session.PeerMeta` which only accepts fields below;
`description: String?`
`icons: List<String>?`
`name: String?`
`url: String?`
Do you have any suggestions to send client meta to the dApp??

**Comment by patrik7** [comment]
Such a fast reply! Thanks

The options are pretty limited, yes :/

At a minimum, the URL could point to the store:
https://play.google.com/store/apps/details?id=com.algorand.android
https://apps.apple.com/us/app/algorand-wallet/id1459898525

The version could be appended as: ?vesrion=1.23 to the URL

Regards

**Comment by mitsinsar** [comment]
Unfortunately this is not a good solution to solve this issue. Also store doesn't support `version` query. 

WalletConnect v2 may solve this in the future.
