### ISSUE TITLE
Transactions returned from WalletConnect encoded differently

### ISSUE THREAD

**Issue by patrik7** [perawallet/pera-wallet#44]
After the transactions are sent for user's signature thru the Wallet Connect and are signed, they come back:

It seems the iOS version returns the transactions as base64 encoded string
While Android returns them as UInt8Arrays

Happens for regular Payment transactions.

You can easily convert from one to another, but it's inconsistent, and since you do not know against which version you connected to: https://github.com/algorand/algorand-wallet/issues/41

It's tedious to deal with.

I would vote to use the base64 encoding, as that's the same format transactions were submitted in.

**Comment by taylanpince** [comment]
@sakkaras @artizco Can you please review this?

**Comment by yigitguler** [comment]
This is fixed.
