### ISSUE TITLE
Cannot see all accounts when selecting an account to receive algos or connect to WalletConnect

### ISSUE THREAD

**Issue by MacroChip** [perawallet/pera-wallet#49]
I'm on Android. Haven't tested iOS
1. Click into an account's details
2. Tap "send"
3. Tap "Accounts" in the To section
Cannot see all accounts when scrolling down

This is the same for choosing a wallet to connect to WalletConnect.
Note: This problem does not exist when choosing a sender account from the main screen "send". It only appears in Send Algos screen when picking a receiver.

**Comment by Devjohn12** [comment]
Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by barnjamin** [comment]
@taylanpince ^^ Spam link, please delete the comment
