### ISSUE TITLE
Export accounts

### ISSUE THREAD

**Issue by 2i2i** [perawallet/pera-wallet#51]
This would be very useful, e.g. to "transport" accounts across devices.

Either via a 'copy to clipboard' button.

Or add a qr code method: show qr code of passphrase, read qr code to recover account.

**Comment by 2i2i** [comment]
from a security perspective, showing a QR code (containing private keys) is no less secure vs. showing the private keys listed of which users can take screenshots (or pics)

the QR code could be considered an obfuscation, but no more (and obfuscation is not security)

Google Auth allows exactly this ~ export account private keys via (presumably encrypted) 3 QR codes ~ these 3 can be scanned on another device and all keys are reimported

Currently, typing the secret key (secret words) is very tedious, when having many accounts

**Comment by yigitguler** [comment]
The fix is live. You can use Algorand secure backup feature.
