### ISSUE TITLE
CSV Export - Cannot determine asset represented by "Amount" field without exporting all CSVs for all assets.

### ISSUE THREAD

**Issue by StickyThwomp** [perawallet/pera-wallet#52]
Using the CSV export feature of the Andoid wallet, it is not possible to determine the asset that the "Amount" column refers to without factoring in all possible exported CSV files.

For example:

- When exporting from the Algo "card view" in the wallet, all transactions regardless of the ASA ID are exported. This includes transactions who's "Amount" is in units of an ASA, not ALGO. This may be a bug on its own though, as the filtered view presented in the App does not show these transactions.
- When exporting from an ASA "card view" in the wallet, only transactions with that ASA ID are shown.

Thus, the only way to know which asset each amount corresponds to is to subtracting all entries found in the ASA export files from the core algo file. Once this is done, the only transactions remaining in the main CSV file will be in Algos.

This could likely be best fixed by adding a column for the ASA ID.

**Comment by taylanpince** [comment]
@StickyThwomp Just wanted to let you know that we are aware of this issue and a fix is coming soon.
