### ISSUE TITLE
Algorand mobile walletconnect on vanillaJs /HTML

### ISSUE THREAD

**Issue by Samuellyworld** [perawallet/pera-wallet#58]
- Is there a way to integrate algorand mobile wallet and  QR code modal with vanilla js/html instead of using ReactJs or frameworks?
- i tried to minify the npm module to es5 using browserify, babel and webpack. I keep getting errors.
- I also used CDN like unpkg and jsdeliver, it also shows module error.
- If there is a provided CDN link that I can link to html `script` tag for both `@walletconnect/client` and `algorand-mobile-qrcode-modal` instead of using `ReactJs or Js frameworks`, I will appreciate. @jasonpaulos @cce @winder @sshravan @tolikzinovyev

**Comment by taylanpince** [comment]
Going forward the recommended way of integration is Pera Connect: https://github.com/perawallet/connect
