### ISSUE TITLE
Latest version crashing on iPad

### ISSUE THREAD

**Issue by AustP** [perawallet/pera-wallet#61]
I use the app on my iPad. I have been testing a dApp on testnet. I used the old version before and it worked fine. The new version crashes 95% of the time I view the algo transaction history for my account. The testnet account I use is: GEMOJ3P6FUP2J2HRV3Y6NVHWH56OOW2OOTGTOZIV6MVXUW335BWIXZFOGY.

**Comment by taylanpince** [comment]
This seems to be resolved now, however please note that we don't currently support iPads. We do no testing on them.
