### ISSUE TITLE
Inner transactions not showing up in transaction history

### ISSUE THREAD

**Issue by AustP** [perawallet/pera-wallet#62]
When viewing the algo transaction history in the app, it doesn't account for all algos flowing into and out of my account.

Consider this transaction: https://testnet.algoexplorer.io/tx/FOERLHPJIBJ63YSQQJDRMJUYQGVQ272TZDUQIYF67IBZ3FQDM7CQ

It funds my test account with 0.929 Algo but that doesn't show up in the app. I would expect to see that amount show up as a received amount in the history.

**Comment by ThomasDev62** [comment]
Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by barnjamin** [comment]
Spam ^

**Comment by AustP** [comment]
@barnjamin what do you mean?

**Comment by barnjamin** [comment]
> Spam ^

@AustP Sorry, no! There was a spam comment here but it was deleted and for some reason doesn't show up in history

**Comment by AustP** [comment]
Haha that's hilarious! I had been out on vacation so I missed the other comment completely and was scratching my head trying to figure out if you had a typo or something. Anyways, thanks for the clarification. =]
