### ISSUE TITLE
'+ Add Account' and 'Arrange List' needs close button

### ISSUE THREAD

**Issue by 2i2i** [perawallet/pera-wallet#63]
Clicking on the "3 dots" menu, leads to a bottom sheet with '+ Add Account' and 'Arrange List'.

For me, there is no way out of that page - needs a cancel/back/close butto

This is macOS

<img width="284" alt="Screenshot 2022-02-24 at 21 50 56" src="https://user-images.githubusercontent.com/89938440/155655803-e10785af-55b9-41d5-baff-2eba7b91ca84.png">
n

**Comment by taylanpince** [comment]
You can swipe down or tap on the light gray "handle" at the top of the modal sheet. That said, we noticed this confusing UX as well and resolved it for our next releases. With the 5.3.0 releases you will be able to tap on the empty space as well to close the sheet.
