### ISSUE TITLE
Assets showing up as "Unnamed" in Pera wallet

### ISSUE THREAD

**Issue by cbaunach** [perawallet/pera-wallet#65]
![Screenshot_20220228-082706](https://user-images.githubusercontent.com/89322349/156000990-45dddad7-44eb-4486-ae4b-3914f9c551e6.png)
Hello, I've noticed that asset 74994149 shows up as Unnamed and without a symbol in the Pera wallet (in addition to ones like it), but if I take my wallet address (`POT2L4UWCTTMFPKQ7NLEUNC3GP6Q7VBNP4OQVUBX7YHD67FR2NUFTK6FA4`) and go over to algoexplorer they show up with their names and symbols.
![Screenshot from 2022-02-28 08-34-32](https://user-images.githubusercontent.com/89322349/156001157-e5316d40-6419-472b-810c-ec2f8a6f378c.png)
https://testnet.algoexplorer.io/address/POT2L4UWCTTMFPKQ7NLEUNC3GP6Q7VBNP4OQVUBX7YHD67FR2NUFTK6FA4
https://testnet.algoexplorer.io/asset/74994149

**Comment by taylanpince** [comment]
We've tracked this down to the `name` field for the ASA being empty. We currently don't fallback to the `name-b64` field. Our API team is working on adding this support.
