### ISSUE TITLE
Node Settings selection is buggy (iOS 15.2)

### ISSUE THREAD

**Issue by gabrielkuettel** [perawallet/pera-wallet#67]
In Developer Settings -> Node Settings, switching between MainNet and TestNet is buggy. 

A modal with a loading spinner briefly appears, but the settings don't take effect until you go back to the previous screen, and then return to the Node Settings screen again. 

Same issue on multiple devices using iOS 15.2.

**Comment by taylanpince** [comment]
This is now resolved.
