### ISSUE TITLE
Add New Asset doesn't support searching by symbol

### ISSUE THREAD

**Issue by every-time** [perawallet/pera-wallet#68]
When going to the Add New Asset panel, I cannot search for assets by their symbol. For example, searching for "yldy" has no results.

**Comment by taylanpince** [comment]
Thank you, this will be added soon.

**Comment by taylanpince** [comment]
This is now added.

**Comment by every-time** [comment]
This has been fixed on the "Add New Asset" panel; however, this issue still persists under "Remove Assets"/"Manage Assets".

**Comment by taylanpince** [comment]
Just confirmed that this will be resolved with the next version as well (5.3.0)

**Comment by every-time** [comment]
> This has been fixed on the "Add New Asset" panel; however, this issue still persists under "Remove Assets"/"Manage Assets".

On the 5.3.0 version (Android), the problem as described above still persists.

**Comment by taylanpince** [comment]
Thanks for the update – It looks like that PR didn't get merged into 5.3.0. Should be in the next release.
