### ISSUE TITLE
Wallet Connect QR Integration

### ISSUE THREAD

**Issue by jonathansmirnoff** [perawallet/pera-wallet#69]
Add deep link to Pera wallet in Wallet Connect. Please look at this example PR as an example: https://github.com/WalletConnect/walletconnect-monorepo/pull/381/commits/2e2c39285ef6f69675808081226ff8b97e1d45b2

**Comment by BenedictWHD** [comment]
Yes please! 

I am having issues when an iOS device is trying to connect to a website with WalletConnect. (website is on the mobile devices browser)

On android you get a "connect" button and works great, on iOS you get a list of wallets and Pera is not one of them. 

So seems impossible to connect to Pera when on a website that wants you to connect with WalletConnect?
