### ISSUE TITLE
UI: Typing in Amount starts from µALGO, not ALGO

### ISSUE THREAD

**Issue by HashMapsData2Value** [perawallet/pera-wallet#7]
In the app when it comes to sending ALGO and you have to type in the amount, you have to type in "1" + "0" + "0" + "0" + "0" + "0" + "0" just to get to 1 ALGO. Instead, it would be nicer if we only had to type in "1". And for smaller denominations, e.g. 0.001, we would instead type "0" + "." + "0" + "0" + "1".

**Comment by taylanpince** [comment]
This is no longer applicable.
