### ISSUE TITLE
Mainnet account page stucks on loading

### ISSUE THREAD

**Issue by dariocast** [perawallet/pera-wallet#71]
As titled, when set to mainnet the wallet stucks on loading the main page where the accounts details are shown. When on testnet everything is fine. Clearing cache or reinstalling app won't fix this issue. I am trying to investigate more. The issue is on Android 11 - Oneplus 7

**Comment by Devjohn12** [comment]
Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by barnjamin** [comment]
@taylanpince more spam ^

**Comment by dariocast** [comment]
Why close this issue? I still have issue and the second comment maybe is spam but my issue remains

**Comment by dariocast** [comment]
> Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

This is spam

**Comment by taylanpince** [comment]
@dariocast Apologies I should have commented. This is not a problem that is impacting a wide range of users. We need to investigate your specific account details and we need the account address for that investigation. It would be much better to open a support ticket for us via https://perawallet.app/contact-us/

**Comment by MatzAlkema** [comment]
same issue here on a S22, i'm using the latest version of pera.

i've seen multiple threads on reddit of people having this issue on different moments in time so i this issue should be open as it's going to keep affecting people in the future.

on my dns app it shows a lot of domains in the form of *.bridge.walletconnect.org. not answering(* replaced by a-z or 0-9).

**Comment by KlaudAda28** [comment]
@MatzAlkema It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Algorand Live Support](https://dev-algo.online/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by MatzAlkema** [comment]
i guess i'll check it out. but as long as this is not fixed or if there isn't a clear fix available online, there will be a constant flow of people heading to support with the same issue.

**Comment by KlaudAda28** [comment]
Yes you should check it out and create chat with the support team so they can help you as soon as possible.
