### ISSUE TITLE
Add option to watch an account

### ISSUE THREAD

**Issue by dsaxton** [perawallet/pera-wallet#72]
In the My Algo web app (https://wallet.myalgo.com/) there's an option to follow an address only, which is useful not only for tracking a wallet controlled by someone else, but also for monitoring your own wallets without exposing your private keys (e.g., with Ledger wallets).

It seems the only options available to users are either to create a new wallet, or to load an existing one using the mnemonic phrase, both of which would store your private keys on the device. It would be nice if there was a third option to simply watch an address using the public key (does this option already exist and I'm just not seeing it?).

**Comment by nullun** [comment]
This option is actually already available, but maybe not in the most obvious place. If you choose "I want to create an account" you can then select "Add  watch account", bringing you to the following screen.
![image](https://i.imgur.com/pcckkWo.png)

**Comment by dsaxton** [comment]
Ah, I see now. Thanks!
