### ISSUE TITLE
Send transaction by QR deep link not working on iOS

### ISSUE THREAD

**Issue by ldtorres-randlabs** [perawallet/pera-wallet#73]
When I try to send an transaction using QR with iOS application and the app opens, it is not taking the query params (note, amount) in the url.

Example: 

![image](https://user-images.githubusercontent.com/89399858/161820407-3c12d46a-7c9a-44b2-8abc-0e99910d336f.png)

Deep link: algorand://VLXIDAD6V2ZDBQAALAGVE277GBGXSBX22XKJJ4E7TW27COKFISUF45R5UM?note=994661&amount=0

**Comment by Devjohn12** [comment]
Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by barnjamin** [comment]
@taylanpince another spam ^

**Comment by taylanpince** [comment]
This will be resolved with the next release (5.3.0) – QR code above is working well on our internal test version.
