### ISSUE TITLE
WEBP support for NFT gallery

### ISSUE THREAD

**Issue by runvnc** [perawallet/pera-wallet#74]
Hello, so I run https://algonfts.art, which is a tool for generating and minting Arc69 NFTs with random combinations of traits (and images) as well as LiveScript for procedural generation.  While developing version 2 of my engine, I noticed that WEBP files can be more than 10 times smaller than PNG output. I researched and discovered that compatibility and support is now very good for WEBP. So all images are generated and minted as WEBP in my new engine.

I don't know if this is still relevant https://stackoverflow.com/questions/32091675/how-to-use-webp-image-in-uiimageview-swift since it is from several years ago.

**Comment by ThomasDev62** [comment]
Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by barnjamin** [comment]
@taylanpince spam ^

**Comment by taylanpince** [comment]
WebP is now fully supported.
