### ISSUE TITLE
Allow to close account (send max)

### ISSUE THREAD

**Issue by 2i2i** [perawallet/pera-wallet#76]
Currently, the 'MAX' button actually fills in the full amount, but 'Next' then gives an error.
User should be able to send ALL, thereby closing the account (assuming no opt-ins etc.)

**Comment by 2i2i** [comment]
> yes, Send Max doesnt work as expected. it should remove 0.001algo from the computed total so the txn can run.

Actually it needs to deduct an amount depending on the smart contracts and ASAs that the account is opt-ed into.

Additionally, one needs to be able to close the account (close-up), which opts-out of all SCs and ASAs and then sends all minus the txn fee to the target.

**Comment by taylanpince** [comment]
Thank you, we are actively working on resolving this.

**Comment by yigitguler** [comment]
The fix is live.
