### ISSUE TITLE
Sending "max" fills in the incorrect amounth

### ISSUE THREAD

**Issue by fruitmans** [perawallet/pera-wallet#78]
https://user-images.githubusercontent.com/11027774/170045873-35064524-2e15-47e4-b0f1-a97c1aa5ebd1.mp4

I use PeraWallet on my Google Pixel 2XL but encounter the following issue: 

When i try to do a send transaction, the button MAX fills i the incorrect mount for the transaction. e.g. whe the balance is 1520 it is represented in text as 1,5K an the filled in amount will be 1,5. See the video for explanation. 

My phone is configured for the Dutch language.

**Comment by FankDev** [comment]
@fruitmans Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by taylanpince** [comment]
Thank you for this detailed report, we are investigating.

**Comment by taylanpince** [comment]
This is now fixed with the 5.3.0 series.
