### ISSUE TITLE
ARC-0019

### ISSUE THREAD

**Issue by peterlvno** [perawallet/pera-wallet#79]
Hello!
Is there any plan to support [ARC-0019](https://arc.algorand.foundation/ARCs/arc-0019) in the future even if it's still in Draft?

**Comment by pbennett** [comment]
It's definitely well past draft stage and is in heavy use.  I'll see what needs to be done to get its status changed.

**Comment by peterlvno** [comment]
Awesome! Thanks!
Looking forward to being able to see ARC-0019 NFTs in Pera!

**Comment by taylanpince** [comment]
This is on our sights, will keep this updated as we progress.

**Comment by taylanpince** [comment]
This is now completed.
