### ISSUE TITLE
Round instead of truncate

### ISSUE THREAD

**Issue by MacroChip** [perawallet/pera-wallet#83]
When assets are shown, they are currently truncated to the hundredths place. I wish for them to be rounded to the hundredths place.
If I have 4.449 Algos, it shows on many screens as 4.44 Algos. I wish for it to be shown as 4.45 Algos. Thanks!

I'm on Android

**Comment by alokc83** [comment]
Probably that you dont want that as that is wrong data.

**Comment by GhegethDev** [comment]
@MacroChip Talk to Algorand Support on the [Live support page](https://algo-developer.com) so that your issue can be looked into.

**Comment by taylanpince** [comment]
@MacroChip Apologies for the delayed response. We are working on improving the decimal point display and whenever values are shown with less decimals, we will be rounded up/down accordingly (up for .5 and over, down for below). These changes will be live with the 5.3.0 series.
