### ISSUE TITLE
WalletConnect tx signing problem on iOS or Android

### ISSUE THREAD

**Issue by ZitRos** [perawallet/pera-wallet#84]
Hello!

You have iOS doing not quite good as Android when it comes to signing transactions. Our DApp integrated with Pera Android throws an error on iOS since it doesn't follow the same protocol and returns strings instead of an encoded object. Please fix!

Below some context from our engineers.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/4989256/176871106-f5b8292a-8ced-4ddb-ad48-8cb8fb4c8707.png">

Reference code of the client application:

```javascript
const group = txns.map(({txn, signers}) => (signers.length > 0) ? {txn} : {txn, signers: []})
const result = await wallet.sendCustomRequest({
    id: Date.now() + Math.floor(Math.random() * 1000),
    jsonrpc: "2.0",
    method: "algo_signTxn",
    params: [group],
});

// This errors on iOS: // const signed = result.filter(txn => txn != undefined).map(txn => btoa(String.fromCharCode.apply(null, txn)))
// Since Pera wallet on iOS sends txn as string:
const signed = result
    .filter(txn => txn != undefined)
    .map(txn => typeof txn === "string" ? txn : btoa(String.fromCharCode.apply(null, txn)));
```

This should be enough for engineers to test and fix the issue.

**Comment by mucahit** [comment]
Hey @ZitRos,

Our iOS app returns the signed txns in bas64 format(which is expected), so you need to handle that on your own. I'd suggest you switch to [`@perawallet/connect`](https://www.npmjs.com/package/@perawallet/connect) package as soon as possible, so you don't have to deal with the signing infra on your side.

Anyways, here is an example to fix your implementation

```javascript
const signed = result
    .filter(txn => txn != undefined)
    .map(txn => typeof txn === "string" ? base64ToUint8Array(txn) : btoa(String.fromCharCode.apply(null, txn)));
```

```javascript
function base64ToUint8Array(data: string) {
  return Uint8Array.from(window.atob(data), (value) => value.charCodeAt(0));
}
```

I hope that helps.

**Comment by ZitRos** [comment]
@mohammad-beheshti worked on this so he might provide further details.

Let's please identify whether:

- this is our implementation issue (we have a single codebase so I assume not)
- this is your issue where Android and iOS apps don't follow the same standard and return different things after signing

**Comment by taylanpince** [comment]
@ZitRos @mohammad-beheshti We strongly recommend that you switch to Pera's official WalletConnect library (https://github.com/perawallet/connect). It fixes several issues that we've encountered with other libraries and will bring new features in the upcoming months.

We will nevertheless investigate any discrepancies between iOS and Android apps. However as long as you use the official Pera Connect library you should be OK.

**Comment by ZitRos** [comment]
Thank you for details. Noted.
