### ISSUE TITLE
Make 'Enable Face ID / Touch ID' default true

### ISSUE THREAD

**Issue by 1m1-github** [perawallet/pera-wallet#87]
, if it is not yet.

Since Pera can serve as the ultimate gate to executing complex financial transactions (from any dApp), it is crucial to strengthen the security of this app as much as possible.

This feature would tie the security of the tech that connects a user to the most efficient financial network with its biometrics, or more generally, as secure as their device is.

**Comment by taylanpince** [comment]
This is already enabled by default, however permission from the user is required. As long as the user provides permission for Face ID / Touch ID, it's enabled and user is prompted to enabled it on setup.

One improvement that's coming very soon is enabling Face ID / Touch ID for every transaction, in addition to unlocking the app. This will be added soon.
