### ISSUE TITLE
iOS Add Asset - msgpack decode error [pos 1]

### ISSUE THREAD

**Issue by alejandrolozano** [perawallet/pera-wallet#89]
When try to add any new asset return the error: "msgpack decode error [pos 1]"
I'm using the PurestakeAPI but with Android works perfect ...

thanks in advance

**Comment by taylanpince** [comment]
Can you please provide some more information on this issue @alejandrolozano ? Which ASA are you having issues with? Screenshots or screen recordings would also help.
