### ISSUE TITLE
intermittent appending of xnote  in algorand transaction if specified in transaction URI scheme

### ISSUE THREAD

**Issue by malimohub** [perawallet/pera-wallet#90]
I provided url encoded XNOTE in Algorand transaction URI scheme as per https://developer.algorand.org/docs/get-details/transactions/payment_prompts/, as to prevent sender from modifying note after scanning QR code.

During testing, I scanned QR code and transaction request appeared. if I click "Next" button in wallet and then "Send" button the note is not included in transaction, however if i click "Show Note" and "Done", before hitting "Next" button and then hit "Send" the note is included in transaction.

**Comment by taylanpince** [comment]
@malimohub Thank you for this report. Can you please attach a sample QR code here?

**Comment by malimohub** [comment]
Thanks for the quick response, you can find sample QR code below. asset is on testnet

<img width="498" alt="Screen Shot 2022-07-28 at 3 14 23 PM" src="https://user-images.githubusercontent.com/13194858/181514002-c8311cac-0a4e-4476-ab71-28f574ab33b9.png">

**Comment by taylanpince** [comment]
Thank you so much. I was able to reproduce the issue and we are tracking this internally.

**Comment by malimohub** [comment]
@taylanpince any movement on this ?

**Comment by taylanpince** [comment]
@malimohub Yes, this is being worked on. Fix will be up with one of our upcoming bugfix releases.

**Comment by malimohub** [comment]
any traction on this ticket @taylanpince ?

**Comment by taylanpince** [comment]
@malimohub Still in progress. I just prioritized it to be included in 5.4.1 release (ETA in September)

**Comment by malimohub** [comment]
@taylanpince just checking in on this bug fix / scheduled 5.4.1 release?

**Comment by taylanpince** [comment]
@malimohub Still in progress and scheduled for `5.4.1`. We are a bit delayed with this but should be out this month.

**Comment by taylanpince** [comment]
@malimohub Apologies confirmed that this will be in `5.4.2`

**Comment by malimohub** [comment]
> @malimohub Apologies confirmed that this will be in `5.4.2`

Sweet thanks man, will check it out this week. Appreciate you guys working to get this fix pushed out

**Comment by malimohub** [comment]
@taylanpince did this make it to 5.4.2 ? The xnote still does not seem to get appended to transaction. I see the code was tagged at 5.4.2, was this deployed?

Thanks

**Comment by taylanpince** [comment]
@malimohub Apologies for this, our release planning didn't go as planned here 😅 We had to prioritize some other issues that had to be released earlier, and this one got pushed out. We are going to get the `5.5.0` feature release out in a few days, then we will get `5.5.1` out within 2 weeks which will include this fix (and many others).

**Comment by malimohub** [comment]
ahh i see @taylanpince , is there a work around?

**Comment by taylanpince** [comment]
@malimohub AFAIK there is no workaround. However the fix is coming very soon.

**Comment by yigitguler** [comment]
The fix is live.
