### ISSUE TITLE
After importing an account using mnemonics, account doesn't appear on accounts list

### ISSUE THREAD

**Issue by fionnachan** [perawallet/pera-wallet#91]
After importing an account using mnemonics, account doesn't appear on accounts list

dragging the screen towards the bottom would not refresh it;
going to an existing account's details page and back would not refresh it

it only shows up after I force-closed and reopened the app

iOS 15.6
Pera Wallet Version 5.3.0

**Comment by taylanpince** [comment]
Thanks for the report, we are tracking this internally.
